version: '3.4'

services:
  nbapick4me.api:
    image: ${DOCKER_REGISTRY-}moneytrackerapi
    container_name: MoneyTracker.API
    build:
      context: .
      dockerfile: src/MoneyTracker.API/Dockerfile

  nbapick4me-db:
    image: postgres:latest
    container_name: MoneyTracker.Db
    environment:
      - POSTGRES_DB=moneytracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      -  5432:5432
